micronaut:
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
  application:
    name: micronaut-email-service
  server:
    port: 8085